// COCA-inspired frequency-ranked vocabulary for IELTS candidates.
// Tier 1 = top 500 most frequent (essential); Tier 4 = 2000-3000 (advanced Band 7+).

export type PartOfSpeech = 'noun' | 'verb' | 'adjective' | 'adverb' | 'phrase';

export type VocabWord = {
  word: string;
  pos: PartOfSpeech;
  definition: string;
  definitionBn: string;
  example: string;
  collocations: string[];
  tier: 1 | 2 | 3 | 4;
  ieltsTask?: 'writing' | 'speaking' | 'both';
};

export const VOCAB_WORDS: VocabWord[] = [
  // ── TIER 1 — Most Common (essential for all tasks) ───────────────────────
  {
    word: 'achieve',
    pos: 'verb',
    definition: 'To successfully reach a goal through effort.',
    definitionBn: 'প্রচেষ্টার মাধ্যমে লক্ষ্য অর্জন করা।',
    example: 'Students who practise daily tend to achieve higher band scores.',
    collocations: ['achieve a goal', 'achieve success', 'achieve balance'],
    tier: 1,
    ieltsTask: 'both',
  },
  {
    word: 'affect',
    pos: 'verb',
    definition: 'To have an influence or impact on something.',
    definitionBn: 'কোনো কিছুর উপর প্রভাব ফেলা।',
    example: 'Pollution affects the health of millions of people in urban areas.',
    collocations: ['affect health', 'negatively affect', 'deeply affect'],
    tier: 1,
    ieltsTask: 'both',
  },
  {
    word: 'approach',
    pos: 'noun',
    definition: 'A way of dealing with a problem or situation.',
    definitionBn: 'কোনো সমস্যা বা পরিস্থিতি সামলানোর পদ্ধতি।',
    example: 'A balanced approach to diet and exercise is key to good health.',
    collocations: ['take an approach', 'balanced approach', 'traditional approach'],
    tier: 1,
    ieltsTask: 'writing',
  },
  {
    word: 'argue',
    pos: 'verb',
    definition: 'To give reasons in support of or against something.',
    definitionBn: 'কোনো বিষয়ের পক্ষে বা বিপক্ষে যুক্তি দেওয়া।',
    example: 'Many experts argue that renewable energy is the only sustainable option.',
    collocations: ['argue that', 'strongly argue', 'argue against'],
    tier: 1,
    ieltsTask: 'writing',
  },
  {
    word: 'cause',
    pos: 'noun',
    definition: 'The reason why something happens.',
    definitionBn: 'কোনো কিছু ঘটার কারণ।',
    example: 'The main cause of traffic congestion in Dhaka is the rapid growth of vehicles.',
    collocations: ['main cause', 'cause of', 'root cause'],
    tier: 1,
    ieltsTask: 'writing',
  },
  {
    word: 'consider',
    pos: 'verb',
    definition: 'To think carefully about something before deciding.',
    definitionBn: 'সিদ্ধান্ত নেওয়ার আগে সতর্কভাবে চিন্তা করা।',
    example: 'Governments must consider the long-term effects of their environmental policies.',
    collocations: ['consider carefully', 'consider options', 'widely considered'],
    tier: 1,
    ieltsTask: 'both',
  },
  {
    word: 'create',
    pos: 'verb',
    definition: 'To bring something into existence.',
    definitionBn: 'কোনো কিছু তৈরি করা বা অস্তিত্বে আনা।',
    example: 'Technology has created new opportunities for education worldwide.',
    collocations: ['create jobs', 'create opportunities', 'create problems'],
    tier: 1,
    ieltsTask: 'both',
  },
  {
    word: 'develop',
    pos: 'verb',
    definition: 'To grow, advance, or make more elaborate over time.',
    definitionBn: 'সময়ের সাথে বৃদ্ধি পাওয়া বা উন্নত করা।',
    example: 'Children who read widely develop stronger vocabulary and critical thinking skills.',
    collocations: ['develop skills', 'rapidly develop', 'develop a plan'],
    tier: 1,
    ieltsTask: 'both',
  },
  {
    word: 'effect',
    pos: 'noun',
    definition: 'A change produced by a cause; the result of an action.',
    definitionBn: 'কোনো কারণের ফলে যে পরিবর্তন হয়; কোনো কাজের ফলাফল।',
    example: 'The positive effects of exercise on mental health are well documented.',
    collocations: ['have an effect', 'negative effect', 'side effect'],
    tier: 1,
    ieltsTask: 'writing',
  },
  {
    word: 'focus',
    pos: 'verb',
    definition: 'To concentrate attention or effort on something.',
    definitionBn: 'কোনো বিষয়ে মনোযোগ বা প্রচেষ্টা কেন্দ্রীভূত করা।',
    example: 'This essay will focus on the economic benefits of tourism.',
    collocations: ['focus on', 'main focus', 'focus attention'],
    tier: 1,
    ieltsTask: 'writing',
  },
  {
    word: 'impact',
    pos: 'noun',
    definition: 'A strong effect or influence on something.',
    definitionBn: 'কোনো কিছুর উপর শক্তিশালী প্রভাব।',
    example: 'Social media has had a significant impact on how young people communicate.',
    collocations: ['significant impact', 'negative impact', 'have an impact on'],
    tier: 1,
    ieltsTask: 'both',
  },
  {
    word: 'increase',
    pos: 'verb',
    definition: 'To become or make greater in amount, size, or degree.',
    definitionBn: 'পরিমাণ, আকার বা মাত্রায় বৃদ্ধি পাওয়া বা করা।',
    example: 'The graph shows that internet usage increased dramatically between 2010 and 2020.',
    collocations: ['significantly increase', 'increase in', 'steadily increase'],
    tier: 1,
    ieltsTask: 'writing',
  },
  {
    word: 'indicate',
    pos: 'verb',
    definition: 'To point to or suggest something.',
    definitionBn: 'কোনো কিছু নির্দেশ করা বা ইঙ্গিত দেওয়া।',
    example: 'The data indicates a clear link between education and economic growth.',
    collocations: ['clearly indicate', 'indicate that', 'strongly indicate'],
    tier: 1,
    ieltsTask: 'writing',
  },
  {
    word: 'involve',
    pos: 'verb',
    definition: 'To include as a necessary part or require participation.',
    definitionBn: 'প্রয়োজনীয় অংশ হিসেবে অন্তর্ভুক্ত করা বা অংশগ্রহণ প্রয়োজন হওয়া।',
    example: 'Learning a language involves consistent daily practice.',
    collocations: ['involve risk', 'actively involve', 'involve people in'],
    tier: 1,
    ieltsTask: 'both',
  },
  {
    word: 'lead',
    pos: 'verb',
    definition: 'To guide, or to result in a consequence.',
    definitionBn: 'পরিচালিত করা, বা কোনো পরিণতির কারণ হওয়া।',
    example: 'Poor diet can lead to serious health problems in the long term.',
    collocations: ['lead to', 'lead the way', 'ultimately lead'],
    tier: 1,
    ieltsTask: 'writing',
  },
  {
    word: 'provide',
    pos: 'verb',
    definition: 'To supply or make available something needed.',
    definitionBn: 'প্রয়োজনীয় কিছু সরবরাহ করা বা উপলব্ধ করা।',
    example: 'The government should provide affordable healthcare for all citizens.',
    collocations: ['provide support', 'provide access', 'provide evidence'],
    tier: 1,
    ieltsTask: 'writing',
  },
  {
    word: 'require',
    pos: 'verb',
    definition: 'To need something as essential or obligatory.',
    definitionBn: 'কোনো কিছুকে অপরিহার্য হিসেবে প্রয়োজন হওয়া।',
    example: 'Most universities require a minimum IELTS score of 6.5.',
    collocations: ['require attention', 'require effort', 'as required'],
    tier: 1,
    ieltsTask: 'writing',
  },
  {
    word: 'suggest',
    pos: 'verb',
    definition: 'To put forward an idea for consideration.',
    definitionBn: 'বিবেচনার জন্য একটি ধারণা উপস্থাপন করা।',
    example: 'Research suggests that bilingual children have stronger cognitive skills.',
    collocations: ['strongly suggest', 'suggest that', 'evidence suggests'],
    tier: 1,
    ieltsTask: 'writing',
  },
  {
    word: 'significant',
    pos: 'adjective',
    definition: 'Important enough to be worth attention; large or notable.',
    definitionBn: 'মনোযোগ দেওয়ার মতো গুরুত্বপূর্ণ; বড় বা উল্লেখযোগ্য।',
    example: 'There has been a significant rise in the number of online learners since 2020.',
    collocations: ['significant increase', 'significant change', 'highly significant'],
    tier: 1,
    ieltsTask: 'both',
  },
  {
    word: 'therefore',
    pos: 'adverb',
    definition: 'As a consequence; for that reason.',
    definitionBn: 'ফলস্বরূপ; সেই কারণে।',
    example: 'The population is ageing; therefore, healthcare costs are expected to rise.',
    collocations: ['therefore, it is', 'and therefore', 'therefore we can'],
    tier: 1,
    ieltsTask: 'writing',
  },

  // ── TIER 2 — Intermediate Academic ──────────────────────────────────────
  {
    word: 'acquire',
    pos: 'verb',
    definition: 'To gain or develop a skill, habit, or quality over time.',
    definitionBn: 'সময়ের সাথে কোনো দক্ষতা বা অভ্যাস অর্জন করা।',
    example: 'Children acquire language most easily before the age of ten.',
    collocations: ['acquire skills', 'acquire knowledge', 'acquire language'],
    tier: 2,
    ieltsTask: 'both',
  },
  {
    word: 'adapt',
    pos: 'verb',
    definition: 'To change or adjust to suit a new situation.',
    definitionBn: 'নতুন পরিস্থিতির সাথে মানিয়ে নেওয়া বা পরিবর্তন করা।',
    example: 'Businesses must adapt quickly to changes in consumer behaviour.',
    collocations: ['adapt to', 'adapt quickly', 'adapt strategies'],
    tier: 2,
    ieltsTask: 'both',
  },
  {
    word: 'assess',
    pos: 'verb',
    definition: 'To evaluate or estimate the nature, value, or quality of something.',
    definitionBn: 'কোনো কিছুর প্রকৃতি, মান বা গুণ মূল্যায়ন করা।',
    example: 'Teachers assess students through a combination of exams and coursework.',
    collocations: ['assess performance', 'critically assess', 'assess the impact'],
    tier: 2,
    ieltsTask: 'writing',
  },
  {
    word: 'consequence',
    pos: 'noun',
    definition: 'A result or outcome of an action or situation.',
    definitionBn: 'কোনো কাজ বা পরিস্থিতির ফলাফল।',
    example: 'One consequence of urbanisation is the loss of agricultural land.',
    collocations: ['serious consequences', 'consequence of', 'as a consequence'],
    tier: 2,
    ieltsTask: 'writing',
  },
  {
    word: 'contribute',
    pos: 'verb',
    definition: 'To give or supply something in order to help achieve a result.',
    definitionBn: 'কোনো ফলাফল অর্জনে সাহায্য করার জন্য কিছু দেওয়া।',
    example: 'Exercise contributes significantly to mental as well as physical wellbeing.',
    collocations: ['contribute to', 'greatly contribute', 'contribute positively'],
    tier: 2,
    ieltsTask: 'writing',
  },
  {
    word: 'decline',
    pos: 'verb',
    definition: 'To become smaller, fewer, or weaker; to decrease.',
    definitionBn: 'ছোট, কম বা দুর্বল হওয়া; হ্রাস পাওয়া।',
    example: 'The graph shows that the number of smokers declined steadily over the decade.',
    collocations: ['steadily decline', 'sharp decline', 'decline in numbers'],
    tier: 2,
    ieltsTask: 'writing',
  },
  {
    word: 'demonstrate',
    pos: 'verb',
    definition: 'To clearly show or prove something.',
    definitionBn: 'স্পষ্টভাবে কিছু দেখানো বা প্রমাণ করা।',
    example: 'Research has demonstrated that bilingualism improves problem-solving ability.',
    collocations: ['demonstrate that', 'clearly demonstrate', 'demonstrate ability'],
    tier: 2,
    ieltsTask: 'writing',
  },
  {
    word: 'emerge',
    pos: 'verb',
    definition: 'To come into being or become apparent over time.',
    definitionBn: 'সময়ের সাথে অস্তিত্বে আসা বা স্পষ্ট হওয়া।',
    example: 'New industries emerge as technology advances.',
    collocations: ['emerge from', 'gradually emerge', 'emerge as'],
    tier: 2,
    ieltsTask: 'writing',
  },
  {
    word: 'emphasise',
    pos: 'verb',
    definition: 'To give special importance to something.',
    definitionBn: 'কোনো বিষয়কে বিশেষ গুরুত্ব দেওয়া।',
    example: 'The examiner emphasised the importance of a clear thesis statement.',
    collocations: ['strongly emphasise', 'it is important to emphasise', 'emphasise the need'],
    tier: 2,
    ieltsTask: 'writing',
  },
  {
    word: 'establish',
    pos: 'verb',
    definition: 'To set up or lay the foundation of something permanently.',
    definitionBn: 'কোনো কিছু স্থায়ীভাবে প্রতিষ্ঠা করা।',
    example: 'Bangladesh established its first university in Dhaka in 1921.',
    collocations: ['establish a link', 'well established', 'establish guidelines'],
    tier: 2,
    ieltsTask: 'writing',
  },
  {
    word: 'highlight',
    pos: 'verb',
    definition: 'To draw special attention to something important.',
    definitionBn: 'গুরুত্বপূর্ণ কিছুতে বিশেষ মনোযোগ আকর্ষণ করা।',
    example: 'The report highlights the gap between rich and poor in developing nations.',
    collocations: ['highlight the importance', 'clearly highlight', 'highlight concerns'],
    tier: 2,
    ieltsTask: 'writing',
  },
  {
    word: 'maintain',
    pos: 'verb',
    definition: 'To keep in the same condition; to continue over time.',
    definitionBn: 'একই অবস্থায় রাখা; সময়ের সাথে চালিয়ে যাওয়া।',
    example: 'It is difficult to maintain a high level of motivation throughout exam preparation.',
    collocations: ['maintain balance', 'maintain standards', 'maintain contact'],
    tier: 2,
    ieltsTask: 'both',
  },
  {
    word: 'obtain',
    pos: 'verb',
    definition: 'To get or acquire something, especially through effort.',
    definitionBn: 'কিছু পাওয়া বা অর্জন করা, বিশেষত প্রচেষ্টার মাধ্যমে।',
    example: 'Candidates must obtain a band score of 7.0 to qualify for the programme.',
    collocations: ['obtain a score', 'obtain permission', 'obtain information'],
    tier: 2,
    ieltsTask: 'writing',
  },
  {
    word: 'perspective',
    pos: 'noun',
    definition: 'A particular way of thinking about or viewing something.',
    definitionBn: 'কোনো কিছু সম্পর্কে চিন্তা করার বা দেখার একটি নির্দিষ্ট পদ্ধতি।',
    example: 'From an economic perspective, free trade benefits developing nations.',
    collocations: ['from a … perspective', 'different perspectives', 'in perspective'],
    tier: 2,
    ieltsTask: 'both',
  },
  {
    word: 'policy',
    pos: 'noun',
    definition: 'A course of action adopted by a government or organisation.',
    definitionBn: 'কোনো সরকার বা সংস্থার গৃহীত কার্যক্রমের পরিকল্পনা।',
    example: 'Government policy on education needs to address rural schools.',
    collocations: ['government policy', 'public policy', 'introduce a policy'],
    tier: 2,
    ieltsTask: 'writing',
  },
  {
    word: 'promote',
    pos: 'verb',
    definition: 'To support or encourage something actively.',
    definitionBn: 'সক্রিয়ভাবে কিছু সমর্থন বা উৎসাহিত করা।',
    example: 'Schools should promote critical thinking rather than rote memorisation.',
    collocations: ['promote equality', 'actively promote', 'promote health'],
    tier: 2,
    ieltsTask: 'writing',
  },
  {
    word: 'reduce',
    pos: 'verb',
    definition: 'To make smaller or less in amount, degree, or size.',
    definitionBn: 'পরিমাণ, মাত্রা বা আকারে ছোট বা কম করা।',
    example: 'Cycling to work can help reduce both carbon emissions and traffic congestion.',
    collocations: ['significantly reduce', 'reduce costs', 'reduce the risk'],
    tier: 2,
    ieltsTask: 'writing',
  },
  {
    word: 'solution',
    pos: 'noun',
    definition: 'A means of solving a problem.',
    definitionBn: 'কোনো সমস্যা সমাধানের উপায়।',
    example: 'There is no single solution to the problem of climate change.',
    collocations: ['find a solution', 'possible solution', 'long-term solution'],
    tier: 2,
    ieltsTask: 'writing',
  },
  {
    word: 'support',
    pos: 'verb',
    definition: 'To give assistance, encouragement, or evidence to.',
    definitionBn: 'সহায়তা, উৎসাহ বা প্রমাণ দেওয়া।',
    example: 'Several studies support the idea that sleep deprivation impairs memory.',
    collocations: ['strongly support', 'support the argument', 'provide support'],
    tier: 2,
    ieltsTask: 'writing',
  },
  {
    word: 'trend',
    pos: 'noun',
    definition: 'A general pattern or direction of change.',
    definitionBn: 'পরিবর্তনের একটি সাধারণ ধরন বা দিক।',
    example: 'The graph illustrates an upward trend in renewable energy production.',
    collocations: ['upward trend', 'growing trend', 'current trend'],
    tier: 2,
    ieltsTask: 'writing',
  },

  // ── TIER 3 — Upper-Intermediate (Band 6.5–7 range) ───────────────────────
  {
    word: 'acknowledge',
    pos: 'verb',
    definition: 'To accept or admit the truth or existence of something.',
    definitionBn: 'কোনো কিছুর সত্যতা বা অস্তিত্ব স্বীকার করা।',
    example: 'It must be acknowledged that poverty is a complex, multi-dimensional issue.',
    collocations: ['widely acknowledged', 'it must be acknowledged', 'acknowledge the fact'],
    tier: 3,
    ieltsTask: 'writing',
  },
  {
    word: 'alleviate',
    pos: 'verb',
    definition: 'To make suffering, deficiency, or a problem less severe.',
    definitionBn: 'কষ্ট, অভাব বা সমস্যা কম গুরুতর করা।',
    example: 'Better public transport can alleviate traffic congestion in major cities.',
    collocations: ['alleviate poverty', 'alleviate pressure', 'help alleviate'],
    tier: 3,
    ieltsTask: 'writing',
  },
  {
    word: 'compelling',
    pos: 'adjective',
    definition: 'Evoking strong interest, conviction, or attention.',
    definitionBn: 'দৃঢ় আগ্রহ, বিশ্বাস বা মনোযোগ উদ্রেক করা।',
    example: 'The documentary makes a compelling case for switching to plant-based diets.',
    collocations: ['compelling argument', 'highly compelling', 'compelling evidence'],
    tier: 3,
    ieltsTask: 'both',
  },
  {
    word: 'contentious',
    pos: 'adjective',
    definition: 'Causing or likely to cause controversy and disagreement.',
    definitionBn: 'বিতর্ক ও মতভেদ সৃষ্টি করা বা করার সম্ভাবনা রাখা।',
    example: 'Immigration policy remains one of the most contentious issues in modern politics.',
    collocations: ['contentious issue', 'highly contentious', 'contentious debate'],
    tier: 3,
    ieltsTask: 'writing',
  },
  {
    word: 'diverse',
    pos: 'adjective',
    definition: 'Showing a great deal of variety; of different kinds.',
    definitionBn: 'বিভিন্ন ধরনের; প্রচুর বৈচিত্র্য দেখানো।',
    example: 'A diverse workforce brings different experiences and creative approaches to problems.',
    collocations: ['culturally diverse', 'increasingly diverse', 'diverse range of'],
    tier: 3,
    ieltsTask: 'both',
  },
  {
    word: 'enhance',
    pos: 'verb',
    definition: 'To improve or increase the quality, value, or extent of something.',
    definitionBn: 'কোনো কিছুর মান, মূল্য বা পরিধি উন্নত বা বৃদ্ধি করা।',
    example: 'Reading widely can enhance both vocabulary and cultural awareness.',
    collocations: ['enhance skills', 'greatly enhance', 'enhance performance'],
    tier: 3,
    ieltsTask: 'both',
  },
  {
    word: 'inevitable',
    pos: 'adjective',
    definition: 'Certain to happen and impossible to prevent.',
    definitionBn: 'নিশ্চিতভাবে ঘটবে এবং প্রতিরোধ করা অসম্ভব।',
    example: 'As population grows, conflict over water resources may become inevitable.',
    collocations: ['seems inevitable', 'perhaps inevitable', 'inevitable consequence'],
    tier: 3,
    ieltsTask: 'writing',
  },
  {
    word: 'integrate',
    pos: 'verb',
    definition: 'To combine two or more things to form a cohesive whole.',
    definitionBn: 'একটি সংহত সমগ্র গঠনের জন্য দুই বা ততোধিক জিনিস মিলিত করা।',
    example: 'Technology should be integrated into education without replacing human teachers.',
    collocations: ['integrate into', 'fully integrate', 'integrate technology'],
    tier: 3,
    ieltsTask: 'writing',
  },
  {
    word: 'justify',
    pos: 'verb',
    definition: 'To show or prove that something is right or reasonable.',
    definitionBn: 'কোনো কিছু সঠিক বা যুক্তিসঙ্গত তা দেখানো বা প্রমাণ করা।',
    example: 'The government must justify its decision to cut education funding.',
    collocations: ['justify a decision', 'fully justify', 'difficult to justify'],
    tier: 3,
    ieltsTask: 'writing',
  },
  {
    word: 'predominantly',
    pos: 'adverb',
    definition: 'Mainly; for the most part.',
    definitionBn: 'প্রধানত; বেশিরভাগ অংশের জন্য।',
    example: 'The workforce in this sector is predominantly female.',
    collocations: ['predominantly male/female', 'predominantly urban', 'predominantly used'],
    tier: 3,
    ieltsTask: 'writing',
  },
  {
    word: 'sustainable',
    pos: 'adjective',
    definition: 'Able to be maintained over time without damaging the environment.',
    definitionBn: 'পরিবেশের ক্ষতি না করে দীর্ঘমেয়াদে বজায় রাখা সম্ভব।',
    example: 'Solar energy offers a sustainable alternative to fossil fuels.',
    collocations: ['sustainable development', 'environmentally sustainable', 'sustainable solution'],
    tier: 3,
    ieltsTask: 'both',
  },
  {
    word: 'transition',
    pos: 'noun',
    definition: 'The process of changing from one state or condition to another.',
    definitionBn: 'এক অবস্থা থেকে অন্য অবস্থায় পরিবর্তনের প্রক্রিয়া।',
    example: 'The transition from secondary school to university can be challenging.',
    collocations: ['smooth transition', 'in transition', 'transition from … to'],
    tier: 3,
    ieltsTask: 'both',
  },
  {
    word: 'substantial',
    pos: 'adjective',
    definition: 'Of considerable importance, size, or value.',
    definitionBn: 'উল্লেখযোগ্য গুরুত্ব, আকার বা মূল্যের।',
    example: 'There has been a substantial improvement in literacy rates over the past decade.',
    collocations: ['substantial increase', 'substantial evidence', 'substantial number of'],
    tier: 3,
    ieltsTask: 'writing',
  },
  {
    word: 'undermine',
    pos: 'verb',
    definition: 'To weaken or damage gradually, especially from within.',
    definitionBn: 'ধীরে ধীরে দুর্বল বা ক্ষতিগ্রস্ত করা, বিশেষত ভেতর থেকে।',
    example: 'Corruption can undermine public trust in democratic institutions.',
    collocations: ['undermine confidence', 'seriously undermine', 'undermine efforts'],
    tier: 3,
    ieltsTask: 'writing',
  },
  {
    word: 'widespread',
    pos: 'adjective',
    definition: 'Found or distributed over a large area or number of people.',
    definitionBn: 'বড় এলাকা বা বহু মানুষের মধ্যে পাওয়া বা বিতরণ করা।',
    example: 'Smartphone use has become widespread among all age groups.',
    collocations: ['widespread use', 'become widespread', 'widespread concern'],
    tier: 3,
    ieltsTask: 'writing',
  },
  {
    word: 'inequality',
    pos: 'noun',
    definition: 'Difference in social status, wealth, or opportunity.',
    definitionBn: 'সামাজিক মর্যাদা, সম্পদ বা সুযোগে পার্থক্য।',
    example: 'Income inequality is growing in both developed and developing countries.',
    collocations: ['income inequality', 'social inequality', 'reduce inequality'],
    tier: 3,
    ieltsTask: 'writing',
  },
  {
    word: 'furthermore',
    pos: 'adverb',
    definition: 'In addition; as a further point (used to add a supporting idea).',
    definitionBn: 'অতিরিক্তভাবে; আরও একটি বিষয় হিসেবে।',
    example: 'Exercise improves physical health. Furthermore, it reduces stress and anxiety.',
    collocations: ['furthermore, it', 'furthermore, this', 'and furthermore'],
    tier: 3,
    ieltsTask: 'writing',
  },
  {
    word: 'tackle',
    pos: 'verb',
    definition: 'To make a determined effort to deal with a problem.',
    definitionBn: 'কোনো সমস্যা মোকাবেলায় দৃঢ় প্রচেষ্টা করা।',
    example: 'Governments need to tackle air pollution before it becomes a public health crisis.',
    collocations: ['tackle the issue', 'tackle poverty', 'effectively tackle'],
    tier: 3,
    ieltsTask: 'writing',
  },
  {
    word: 'stimulate',
    pos: 'verb',
    definition: 'To cause something to become active or more active.',
    definitionBn: 'কোনো কিছুকে সক্রিয় বা আরও সক্রিয় করে তোলা।',
    example: 'Investment in infrastructure can stimulate economic growth in rural areas.',
    collocations: ['stimulate growth', 'stimulate discussion', 'stimulate the economy'],
    tier: 3,
    ieltsTask: 'writing',
  },
  {
    word: 'notion',
    pos: 'noun',
    definition: 'A belief or idea, especially one that is vague or not fully formed.',
    definitionBn: 'একটি বিশ্বাস বা ধারণা, বিশেষত যেটি অস্পষ্ট।',
    example: 'The notion that women are less capable in STEM fields is a harmful stereotype.',
    collocations: ['the notion that', 'challenge the notion', 'popular notion'],
    tier: 3,
    ieltsTask: 'writing',
  },

  // ── TIER 4 — Advanced (Band 7–8 differentiation) ────────────────────────
  {
    word: 'advocate',
    pos: 'verb',
    definition: 'To publicly recommend or support a cause or policy.',
    definitionBn: 'কোনো কারণ বা নীতি প্রকাশ্যে সমর্থন বা সুপারিশ করা।',
    example: 'Educators increasingly advocate for project-based learning over standardised tests.',
    collocations: ['strongly advocate', 'advocate for', 'advocate change'],
    tier: 4,
    ieltsTask: 'writing',
  },
  {
    word: 'ambiguous',
    pos: 'adjective',
    definition: 'Open to more than one interpretation; not clear.',
    definitionBn: 'একাধিক ব্যাখ্যার জন্য উন্মুক্ত; স্পষ্ট নয়।',
    example: 'The government\'s stance on climate funding remains ambiguous.',
    collocations: ['remain ambiguous', 'deliberately ambiguous', 'morally ambiguous'],
    tier: 4,
    ieltsTask: 'writing',
  },
  {
    word: 'articulate',
    pos: 'adjective',
    definition: 'Able to express thoughts and ideas clearly and effectively.',
    definitionBn: 'চিন্তা ও ধারণা স্পষ্ট এবং কার্যকরভাবে প্রকাশ করতে সক্ষম।',
    example: 'An articulate speaker uses a range of vocabulary and sentence structures.',
    collocations: ['highly articulate', 'articulate response', 'clearly articulate'],
    tier: 4,
    ieltsTask: 'speaking',
  },
  {
    word: 'detrimental',
    pos: 'adjective',
    definition: 'Tending to cause harm or damage.',
    definitionBn: 'ক্ষতি বা ক্ষয়ের প্রবণতা রাখে।',
    example: 'Excessive screen time can be detrimental to children\'s social development.',
    collocations: ['detrimental effect', 'potentially detrimental', 'detrimental to health'],
    tier: 4,
    ieltsTask: 'writing',
  },
  {
    word: 'empirical',
    pos: 'adjective',
    definition: 'Based on observation, experience, and evidence rather than theory.',
    definitionBn: 'তত্ত্বের পরিবর্তে পর্যবেক্ষণ, অভিজ্ঞতা এবং প্রমাণের উপর ভিত্তি করে।',
    example: 'Empirical evidence consistently shows the benefits of early childhood education.',
    collocations: ['empirical evidence', 'empirical research', 'empirical data'],
    tier: 4,
    ieltsTask: 'writing',
  },
  {
    word: 'facilitate',
    pos: 'verb',
    definition: 'To make a process easier or help it happen.',
    definitionBn: 'কোনো প্রক্রিয়া সহজ করা বা ঘটতে সাহায্য করা।',
    example: 'Online platforms facilitate access to education for remote communities.',
    collocations: ['facilitate access', 'facilitate learning', 'greatly facilitate'],
    tier: 4,
    ieltsTask: 'writing',
  },
  {
    word: 'inherent',
    pos: 'adjective',
    definition: 'Existing as a natural, permanent, or essential quality.',
    definitionBn: 'স্বাভাবিক, স্থায়ী বা অপরিহার্য গুণ হিসেবে বিদ্যমান।',
    example: 'There is an inherent tension between economic growth and environmental protection.',
    collocations: ['inherent risk', 'inherent tension', 'inherent problem'],
    tier: 4,
    ieltsTask: 'writing',
  },
  {
    word: 'paradox',
    pos: 'noun',
    definition: 'A statement that seems self-contradictory but may express a deeper truth.',
    definitionBn: 'একটি বিবৃতি যা স্ব-বিরোধী মনে হলেও গভীর সত্য প্রকাশ করতে পারে।',
    example: 'It is a paradox that countries with the most natural resources are often the poorest.',
    collocations: ['an interesting paradox', 'it is a paradox that', 'apparent paradox'],
    tier: 4,
    ieltsTask: 'writing',
  },
  {
    word: 'nuance',
    pos: 'noun',
    definition: 'A subtle difference in meaning, expression, or sound.',
    definitionBn: 'অর্থ, প্রকাশ বা শব্দে একটি সূক্ষ্ম পার্থক্য।',
    example: 'Band 9 writing demonstrates a clear awareness of nuance in complex arguments.',
    collocations: ['subtle nuance', 'nuance of meaning', 'appreciate the nuance'],
    tier: 4,
    ieltsTask: 'both',
  },
  {
    word: 'ubiquitous',
    pos: 'adjective',
    definition: 'Present, appearing, or found everywhere.',
    definitionBn: 'সর্বত্র উপস্থিত, দৃশ্যমান বা পাওয়া যায়।',
    example: 'Smartphones have become ubiquitous in both developed and developing nations.',
    collocations: ['become ubiquitous', 'virtually ubiquitous', 'ubiquitous technology'],
    tier: 4,
    ieltsTask: 'writing',
  },
  {
    word: 'unprecedented',
    pos: 'adjective',
    definition: 'Never done or known before; without historical parallel.',
    definitionBn: 'আগে কখনো করা বা জানা যায়নি; ঐতিহাসিকভাবে অতুলনীয়।',
    example: 'The COVID-19 pandemic caused an unprecedented disruption to global education.',
    collocations: ['unprecedented scale', 'truly unprecedented', 'unprecedented growth'],
    tier: 4,
    ieltsTask: 'writing',
  },
  {
    word: 'viable',
    pos: 'adjective',
    definition: 'Capable of working successfully; feasible.',
    definitionBn: 'সফলভাবে কাজ করতে সক্ষম; সম্ভবপর।',
    example: 'Nuclear energy may be the only commercially viable low-carbon option at scale.',
    collocations: ['commercially viable', 'viable alternative', 'economically viable'],
    tier: 4,
    ieltsTask: 'writing',
  },
  {
    word: 'scrutinise',
    pos: 'verb',
    definition: 'To examine or inspect closely and thoroughly.',
    definitionBn: 'ঘনিষ্ঠভাবে এবং পুঙ্খানুপুঙ্খভাবে পরীক্ষা করা।',
    example: 'The committee will scrutinise the proposals before making a final decision.',
    collocations: ['carefully scrutinise', 'scrutinise the data', 'closely scrutinised'],
    tier: 4,
    ieltsTask: 'writing',
  },
  {
    word: 'eloquent',
    pos: 'adjective',
    definition: 'Fluent, persuasive, and well-expressed in speech or writing.',
    definitionBn: 'বক্তৃতা বা লেখায় সাবলীল, প্রভাবশালী এবং সুচিন্তিতভাবে প্রকাশিত।',
    example: 'An eloquent response in IELTS Speaking Part 3 requires extended reasoning.',
    collocations: ['eloquent speaker', 'highly eloquent', 'eloquent argument'],
    tier: 4,
    ieltsTask: 'speaking',
  },
  {
    word: 'volatile',
    pos: 'adjective',
    definition: 'Liable to change rapidly and unpredictably; unstable.',
    definitionBn: 'দ্রুত এবং অপ্রত্যাশিতভাবে পরিবর্তনের প্রবণতা; অস্থির।',
    example: 'The job market in technology has become increasingly volatile in recent years.',
    collocations: ['volatile market', 'highly volatile', 'volatile situation'],
    tier: 4,
    ieltsTask: 'writing',
  },
  {
    word: 'mitigate',
    pos: 'verb',
    definition: 'To make less severe, serious, or painful.',
    definitionBn: 'কম গুরুতর, গুরুতর বা বেদনাদায়ক করা।',
    example: 'Urban planning strategies can help mitigate the effects of flooding.',
    collocations: ['mitigate risk', 'help mitigate', 'mitigate the effects'],
    tier: 4,
    ieltsTask: 'writing',
  },
  {
    word: 'exacerbate',
    pos: 'verb',
    definition: 'To make an already bad situation worse.',
    definitionBn: 'ইতিমধ্যে খারাপ পরিস্থিতিকে আরও খারাপ করা।',
    example: 'Poor public transport exacerbates inequality by limiting access to employment.',
    collocations: ['exacerbate the problem', 'further exacerbate', 'exacerbate tensions'],
    tier: 4,
    ieltsTask: 'writing',
  },
  {
    word: 'holistic',
    pos: 'adjective',
    definition: 'Dealing with the whole of something rather than just its parts.',
    definitionBn: 'শুধু অংশের পরিবর্তে কোনো কিছুর সমগ্রকে নিয়ে কাজ করা।',
    example: 'A holistic approach to healthcare treats the patient, not just the disease.',
    collocations: ['holistic approach', 'holistic view', 'holistic development'],
    tier: 4,
    ieltsTask: 'writing',
  },
  {
    word: 'pivotal',
    pos: 'adjective',
    definition: 'Of crucial importance in relation to the success of something.',
    definitionBn: 'কোনো কিছুর সাফল্যের ক্ষেত্রে অত্যন্ত গুরুত্বপূর্ণ।',
    example: 'Education plays a pivotal role in breaking the cycle of poverty.',
    collocations: ['pivotal role', 'pivotal moment', 'absolutely pivotal'],
    tier: 4,
    ieltsTask: 'both',
  },
  {
    word: 'disparity',
    pos: 'noun',
    definition: 'A great difference, especially an unfair or unjust one.',
    definitionBn: 'বিশেষত অন্যায় বা অসামঞ্জস্যপূর্ণ একটি বড় পার্থক্য।',
    example: 'The disparity in educational resources between urban and rural schools is striking.',
    collocations: ['stark disparity', 'disparity between', 'growing disparity'],
    tier: 4,
    ieltsTask: 'writing',
  },
];

export const VOCAB_TIERS = [
  { value: 0, label: 'All Words', labelBn: 'সব শব্দ', count: VOCAB_WORDS.length },
  { value: 1, label: 'Tier 1 — Essential', labelBn: 'স্তর ১ — অপরিহার্য', count: VOCAB_WORDS.filter(w => w.tier === 1).length },
  { value: 2, label: 'Tier 2 — Intermediate', labelBn: 'স্তর ২ — মধ্যবর্তী', count: VOCAB_WORDS.filter(w => w.tier === 2).length },
  { value: 3, label: 'Tier 3 — Upper-Intermediate', labelBn: 'স্তর ৩ — উচ্চ-মধ্যবর্তী', count: VOCAB_WORDS.filter(w => w.tier === 3).length },
  { value: 4, label: 'Tier 4 — Advanced', labelBn: 'স্তর ৪ — উন্নত', count: VOCAB_WORDS.filter(w => w.tier === 4).length },
] as const;

export const POS_BADGE: Record<PartOfSpeech, string> = {
  noun: 'bg-blue-100 text-blue-800',
  verb: 'bg-green-100 text-green-800',
  adjective: 'bg-purple-100 text-purple-800',
  adverb: 'bg-orange-100 text-orange-800',
  phrase: 'bg-rose-100 text-rose-800',
};
